### ISSUE TITLE
homeでのpinsの設計をする

### ISSUE THREAD

**Issue by ryohma0510** [team-e-org/backend#200]
## 流れ
- ユーザーがpinを作成する時にタグを手打ちする
- api serverでpinを作成する
- マイクロサービスにpinとtagの情報を投げる
- マイクロサービスを使ってpinとtagがMySQL上で紐づられる
- pinのデータが以下の「DynamoDBについて」のところで説明するみたいに保存される

tag:catのピンが作成されると
tag:cat -> tags_pins -> pins(user_idが入ってる)
と持ってきて、そのuser_idに対して、pinをdynamoDBに突っ込める。
![image](https://user-images.githubusercontent.com/24651683/85517883-aa50c580-b63a-11ea-9491-68e6e038e368.png)

## DynamoDBについて

```
パーティションキー: user_id
ソートキー: pin_id
LSI: created_at テーブル作るときしかできないから気をつける
```

メリット
- ホームpinをユーザーがログインするたびとかに作らなくていい

デメリット
- pinが削除された時にめんどくさい。全てのuser_idに対してpin_idで検索して削除しなければいけない。
GSIを使えばこの問題は解決するけど、お金がかかるのでなしにする。
ちなみにあとでGSIを貼ることは可能
```
GSI
パーティションキー:pin_id
ソートキー: user_id
これで削除したいpin_idを持つデータが検索できるようになる。
```

## 実装の方針

1. API Gatewayを立てる
2. lambdaを立てる
3 pinとタグの関連づけを実装する
4 もう一個ラムダを立ててuser_idの一覧をとってみる
5 dynamoを作成する
6 dynamoにデータを突っ込む

## 相談したいこと
- アーキテクチャ考えたらレビューして欲しい

### 順調なら
2h
### ハマったら
3h

**Comment by maxfie1d** [comment]
ピン作成時にタグを1件も登録しないのは許容できる?
一応確認

**Comment by ryohma0510** [comment]
許容できる！
pinsテーブルにはデータができるけど、
tags, tags_pinsテーブルにデータができないだけかな。

**Comment by coil398** [comment]
大体問題ないと思われる
あとはどの処理を本体で行って、どこからの処理をマイクロサービスにぶん投げるか
タグのアタッチまでは本体で行って、あとはgoroutineでマイクロサービスにぶん投げるとか
ピンだけ追加したらあとはマイクロサービスにぶん投げるか

ここまでやるかは微妙だけどエラー処理どうする？

**Comment by dh9489** [comment]
特に問題ないのかなと！
空白どうするとか、タグ文字列のバリデーションが気になるくらいかな??

**Comment by maxfie1d** [comment]
> 許容できる！
> pinsテーブルにはデータができるけど、
> tags, tags_pinsテーブルにデータができないだけかな。

おｋっす

**Comment by ryohma0510** [comment]
> あとはどの処理を本体で行って、どこからの処理をマイクロサービスにぶん投げるか
> タグのアタッチまでは本体で行って、あとはgoroutineでマイクロサービスにぶん投げるとか
> ピンだけ追加したらあとはマイクロサービスにぶん投げるか

ピンだけ追加したらマイクロサービスに投げるのが、役割がはっきりしてていい気がしている。
タグのアタッチまで行うと、マイクロサービス側の役割が小さくなりすぎると思う。

> ここまでやるかは微妙だけどエラー処理どうする？

エラー処理はちょっとわからない。
エラー処理するなら本体側からマイクローサービスに投げた後に成功かどうか待たなきゃいけないとかになるくらいかな。

**Comment by ryohma0510** [comment]
API Gateway + lambdaで図を書いてみた。
![image](https://user-images.githubusercontent.com/24651683/85977118-e8712f00-ba16-11ea-9924-b5a5bf97d36e.png)



機能的にlambdaを二つに分けるのがいいと思ってる。
何か意見あれば教えてください〜

**Comment by maxfie1d** [comment]
lamda2個あるけど、lambda1を経由してlamda2につなげる必要はあるんだっけ?
並列でもいいなら図でもそう描くといいかな

**Comment by dh9489** [comment]
テンション上がるわ、かっこいい！

ちなみに、Boardsのことに触れられてないけど大丈夫なん？

**Comment by ryohma0510** [comment]
> lamda2個あるけど、lambda1を経由してlamda2につなげる必要はあるんだっけ?
> 並列でもいいなら図でもそう描くといいかな

pinとtagを紐づけてからじゃないと次の処理できないから並列は無理かな！

**Comment by ryohma0510** [comment]
> ちなみに、Boardsのことに触れられてないけど大丈夫なん？

pinとboardの紐付けはbackendでしてるけど、今回は書いていない！
ありがとう！
