### ISSUE TITLE
dynamoを作成する

### ISSUE THREAD

**Issue by ryohma0510** [team-e-org/backend#212]
#200

## TODO
- 複合プライマリキーの設定
- LSI貼る

## 調査
調べることがあったら箇条書きで書いてね。

## 相談したいこと
相談したいことがあったら書いておいてね。

## 見積もり時間
２点見積もりしてね。

### 順調なら
2h
### ハマったら
3h

**Comment by ryohma0510** [comment]
カラム |  
-- | --
user_id | パーティションキー
pin_id | ソートキー
title |  
description |  
url |  
post_user_id |  
iamge_url |  
is_private |  
created_at |  
updated_at |  


LSIに関して
例えば2020-6-22以降とかで取った後に、pin_idを使って
上のインデックスで検索すると、2020-6-22以降のデータだけを取ったりできる。

カラム |  
-- | --
user_id | パーティションキー
created_at | ソートキー
pin_id |

**Comment by ryohma0510** [comment]
LSIに関しては容量制限の10GBに引っかからないように上の３つだけにしようと思ってるんだけど、どうだろう？
何日以降のデータだけを取りたいとかのためにLSI貼ると思ってたんだけど、
前話してたとこと意図が違ってたら教えて欲しい。

**Comment by coil398** [comment]
パーティションキーはuser_id
レンジキー(ソートキー)はpin_idで固定
LSIはcreated_atだけでいけるはず
LSIはあくまで日付ソートのため

**Comment by coil398** [comment]
まぁ、何回でも作り直しできるのでやってみると良いかも
