### ISSUE TITLE
userが持つboard一覧を取得する際に、見つからなければ空の配列を返す

### ISSUE THREAD

**Issue by dh9489** [team-e-org/backend#213]
## TODO
- /users/$id/boards にGETリクエストを送った際に、boardsが見つからなければ空配列を返す

## 相談したいこと
- useridが見つからなくても空配列を返す？（これは要議論？）

## 見積もり時間
２点見積もりしてね。

### 順調なら
30min
### ハマったら
60min

**Comment by ryohma0510** [comment]
> useridが見つからなくても空配列を返す？（これは要議論？）

user_idがない->error
boardsがない->から配列

**Comment by ryohma0510** [comment]
やっぱりこう

user_idに対応したuserがいない->空配列
user_idがpathにない->error
boardsがない->空配列
