### ISSUE TITLE
API設計

### ISSUE THREAD

**Issue by coil398** [team-e-org/backend#4]

**Comment by ryohma0510** [comment]
responseは[hal](http://stateless.co/hal_specification.html)か[jsonapi](https://jsonapi.org/)か

[比較記事](https://sookocheff.com/post/api/on-choosing-a-hypermedia-format/)

どっちもflutterのライブラリはある。
halはAWSでも採用されている。

halの方がシンプル
jsonapiはなるべく一つのレスポンスに関連するレコードも入れるようにして、通信回数が少なくなるようにしている。

今回は軽めなhalにすることにした。

**Comment by ryohma0510** [comment]
やっぱり１ヶ月で終わることを考えるとjsonの形式を決めるのオーバーな気がするのでHALはなしにする
