### ISSUE TITLE
mockでhandlerのテスト

### ISSUE THREAD

**Issue by coil398** [team-e-org/backend#95]

**Comment by ryohma0510** [comment]
POST `"/users/sign-in"`` "/users/sign-up"`
min 3h max 4h
#186

GET `"/pins/{id}"`
min 1.5h max 2.5h
#178 

GET `"/boards/{id}/pins"`
min 2h max 3h
#179

GET `"/users/{id}/boards"`
min 1.5h max 2.5h
#180 

POST `"/boards"`
min 2h max 3h
#181 

POST `"/boards/{id}/pins"`
min 4h max 5h
 - s3のモックが必要
